//alert("i am alert")
// a=confirm("do you want to continue")
// //console.log(a)
// if(a==true){
//     window.location.href(login.html)
// }else{

// }
// p=prompt("your name")
// console.log(p)
a="monday";
switch(a){
    case "monday":
    console.log("week start")
    break;
    

    case "tuesday":
    console.log("2nd day")
   

    case "wensday":
    console.log("3rd day")
    

    case "thursday":
    console.log("4th day")

    
    

}